### ISSUE TITLE
Document that maven must be setup for github packages

### ISSUE THREAD

**Issue by phemmer** [EpiCanard/DuckConfig#3]
Just spent a good amount of time trying to build GlobalMarketChest, which has this repo as a dependency. Maven was complaining that it couldn't find duckconfig in `spigot-repo`. This led to a lot of confusion and was because `spigot-repo` is the first one in the list. After moving `duckconfig-repo` to the first in the list, it started giving a permission error instead.

It turns out the issue is that for maven to download from github, you have to configure a personal access token: https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages

It would probably be a good idea to add this to the readme so that other people don't have to go chasing down the problem.

**Comment by EpiCanard** [comment]
I know this "bug" but I can't push public Access keys, GitHub remove them automatically. If you want to build DuckConfig and GlobalMarketChest you will have first to build spigot from official Buildtools.jar
https://www.spigotmc.org/wiki/buildtools/#what-is-it

Sorry for this issue, I plan to move from GitHub packages to self stored maven repository

**Comment by phemmer** [comment]
I'm not sure I follow. I built GlobalMarketChest fine without having to build spigot.

I'm not suggesting you publish tokens, just to add documentation that users will have to setup their own token. That way they don't have to go diagnosing the problem to try and fix it.

But if it's moving to maven soon, then point is probably moot.

**Comment by EpiCanard** [comment]
Maybe you already built spigot before on your computer and spigot stayed in your maven cache ?

**Comment by EpiCanard** [comment]
It take a little of time but the package DuckConfig is now availabe on a public custom maven repository https://maven.epicanard.com/releases.

I will update GlobalMarketChest to use this repository.

```xml
<repository>
  <id>duckconfig-repo</id>
  <url>https://maven.epicanard.com/releases</url>
</repository>
```
